version: '3.7'
services:
  db:
    image: postgres:15.3-alpine
    volumes:
      - "db_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  redis:
    image: redis:7.0.12-alpine
    ports:
      - "6379:6379"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:password@db:5432
    ports:
      - "3051:3000"
    depends_on:
      - db
      - redis
volumes:
  db_data: